# Generated by Django 2.1.1 on 2018-09-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_has_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default='', max_length=256, verbose_name='确认码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='has_confirmed',
            field=models.BooleanField(default=False, verbose_name='是否验证'),
        ),
    ]
